"""empty message

Revision ID: 4795052e0f8e
Revises: 723f435c5233
Create Date: 2019-07-04 09:19:38.173182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4795052e0f8e'
down_revision = '723f435c5233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('club_name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'club_name')
    # ### end Alembic commands ###
