"""change to text

Revision ID: 49042ad93512
Revises: cf042b55174e
Create Date: 2019-06-27 18:20:42.027884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49042ad93512'
down_revision = 'cf042b55174e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
