"""empty message

Revision ID: b918dc806b55
Revises: 4795052e0f8e
Create Date: 2019-07-11 10:07:45.171954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b918dc806b55'
down_revision = '4795052e0f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('club_active', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('club_number', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('club_place', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'club_place')
    op.drop_column('users', 'club_number')
    op.drop_column('users', 'club_active')
    # ### end Alembic commands ###
